### ISSUE TITLE
Feature request: configure ready timeout from flutter

### ISSUE THREAD

**Issue by MarcPorciuncula** [splitio/flutter-sdk-plugin#82]
Hi there, firstly thanks for providing an SDK for flutter! We really appreciate it.

We've been trying to use the `onTimeout` callback when creating a Split client, but we noticed that some of our customers were getting blocked in our app because neither onTimeout nor onReady / onReadyFromCache were being called.

It seems to be that onTimeout will never be called for most Flutter developers because there's no way to configure the sdk ready timeout from the Flutter plugin, and the default in the native iOS / Android libraries is -1 (never). If I'm correct, the only way to set the sdk ready timeout and use the onTimeout callback is to configure and link native Split factories. 

It would be great if there way to configure the ready timeout from flutter. I'd assume this would best be an option on SplitConfiguration.

Cheers

**Comment by gthea** [comment]
Hi @MarcPorciuncula, version [0.1.6](https://pub.dev/packages/splitio/changelog) which addresses this issue has been released.

Thanks for your contribution
